# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT_iOS_HW1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT_iOS_HW1
  pod 'Alamofire', '~> 5.4'

end
